CREATE TABLE [dbo].[PRODUCT_ORDER_STATUS_RESET](
	Id bigint IDENTITY(1,1) NOT NULL,
	CreatedBy [bigint] NULL,
	CreatedAt [datetime] NULL,
	LastUpdBy [bigint] NULL,
	LastUpdAt [datetime] NULL,
	
	ProductId bigint,
	UserId bigint,
	
	ResetDate DateTime,

	CONSTRAINT PRODUCT_ORDER_STATUS_RESET_P01 PRIMARY KEY CLUSTERED 
	(
		Id
	)
)

alter table [PRODUCT_ORDER_STATUS_RESET] add CONSTRAINT PRODUCT_ORDER_STATUS_RESET_USER_F01 FOREIGN KEY ([UserId]) REFERENCES [USER](Id)
alter table [PRODUCT_ORDER_STATUS_RESET] add CONSTRAINT PRODUCT_ORDER_STATUS_RESET_PRODUCT_F01 FOREIGN KEY ([ProductId]) REFERENCES [PRODUCT](Id)