//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B21C.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDER_PRODUCT = new HashSet<ORDER_PRODUCT>();
        }
    
        public long Id { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> LastUpdBy { get; set; }
        public Nullable<System.DateTime> LastUpdAt { get; set; }
        public string Status { get; set; }
        public string Sender { get; set; }
        public Nullable<int> TotalWeight { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string OrderCode { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Receiver { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public Nullable<bool> FlgAdminLogo { get; set; }
        public string TrackingNo { get; set; }
        public string BookedBy { get; set; }
        public string Shipping { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string ShippingCode { get; set; }
        public Nullable<System.DateTime> PrepareShipmentDate { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> AdditionalDiscount { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Subdistrict { get; set; }
        public Nullable<int> SubdistrictId { get; set; }
        public string BankAccountName { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<decimal> UserPaymentAmount { get; set; }
        public Nullable<decimal> TotalPartnerDiscount { get; set; }
        public Nullable<int> PackedCount { get; set; }
        public string PackingCode { get; set; }
        public Nullable<int> PaymentCode { get; set; }
        public Nullable<System.DateTime> ReceivedPaymentConfirmationAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_PRODUCT> ORDER_PRODUCT { get; set; }
    }
}
