//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B21C.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.ORDER_PRODUCT = new HashSet<ORDER_PRODUCT>();
            this.PRODUCT_IMAGE = new HashSet<PRODUCT_IMAGE>();
            this.SHOPPING_CART = new HashSet<SHOPPING_CART>();
            this.PRODUCT_TRENDING = new HashSet<PRODUCT_TRENDING>();
            this.PRODUCT_STOCK_ACTIVITY = new HashSet<PRODUCT_STOCK_ACTIVITY>();
            this.PRODUCT_ORDER_STATUS_RESET = new HashSet<PRODUCT_ORDER_STATUS_RESET>();
        }
    
        public long Id { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> LastUpdBy { get; set; }
        public Nullable<System.DateTime> LastUpdAt { get; set; }
        public string Status { get; set; }
        public string ProductCode { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Size { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Color { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Sales { get; set; }
        public Nullable<decimal> SalesDiscount { get; set; }
        public Nullable<decimal> ModalPrice { get; set; }
        public Nullable<int> OldStock { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<System.DateTime> PublishAt { get; set; }
        public string Section { get; set; }
        public Nullable<long> CategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_PRODUCT> ORDER_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_IMAGE> PRODUCT_IMAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOPPING_CART> SHOPPING_CART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_TRENDING> PRODUCT_TRENDING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_STOCK_ACTIVITY> PRODUCT_STOCK_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_ORDER_STATUS_RESET> PRODUCT_ORDER_STATUS_RESET { get; set; }
        public virtual PRODUCT_CATEGORY PRODUCT_CATEGORY { get; set; }
    }
}
