//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B21C.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_STATUS()
        {
            this.USERs = new HashSet<USER>();
        }
    
        public long Id { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> LastUpdBy { get; set; }
        public Nullable<System.DateTime> LastUpdAt { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> PointNeeded { get; set; }
        public string IconImage { get; set; }
        public Nullable<decimal> PartnerDiscount { get; set; }
        public string PartnerName { get; set; }
        public string PartnerIconImage { get; set; }
        public Nullable<decimal> RegistrationFee { get; set; }
        public Nullable<decimal> PartnerRegistrationFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERs { get; set; }
    }
}
